# Generated by Django 5.2.4 on 2025-07-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fileprocess_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocess',
            name='site_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
